config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'

  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:destroy, :update]

  def index
    @tasks = Task.all.order(done: :asc, created_at: :desc)
  end

  def create
    Task.create! name: task_params[:name]
    redirect_to action: 'index'
  end

  def destroy
    @task.destroy!
    redirect_to action: 'index'
  end

  def update
    @task.update! task_params
    redirect_to action: 'index'
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def task_checked(task)
    'checked' if task.done
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todapp</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/tasks/index.html.erb
<div class="task-input">
  <%= form_for Task.new do |f| %>
    <div class="input-group">
      <%= f.text_field :name, class: 'form-control', placeholder: 'type task title here...' %>
      <span class="input-group-btn">
        <%= f.submit 'create task', class: 'btn btn-success' %>
      </span>
    </div>
  <% end %>
</div>

<class="list-group" div>
<% @tasks.each do |task| %>
<div class="task-card list-group-item">
  <div class="task-status">
    <%= form_for task do |f| %>
      <%= f.check_box :done %>
    <% end %>
  </div>
  <div class="task-name">
    <h3><%= task.name %></h3>
  </div>
  <div class="task-actions">
    <%= link_to icon(:trash), task_path(task), method: :delete, class: 'text-danger' %>
  </div>
</div>
<% end %>
</div>